yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings

User = get_user_model()


class CreatedModel(models.Model):
    """Абстрактная модель. Добавляет дату создания."""
    created = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        abstract = True


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы сообщений',
        help_text='Введите название группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг группы сообщений',
        help_text='Введите слаг группы',
    )
    description = models.TextField(
        verbose_name='Описание группы сообщений',
        help_text='Введите описание группы сообщений',
    )

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.get_representation_text()

    def get_representation_text(self):
        return self.text[:settings.REPRESENTATION_LENGTH]


class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return self.get_representation_text()

    def get_representation_text(self):
        return self.text[:settings.REPRESENTATION_LENGTH]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='user_author'
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        user_full_name = self.user.get_user_name()
        author_full_name = self.author.get_user_name()
        return f'{user_full_name} подписан на {author_full_name}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        min_text_lenght = 10
        if len(data) < min_text_lenght:
            raise forms.ValidationError(
                f'Маловато будет! Пост должен содержать не менее '
                f'{min_text_lenght} символов.'
            )
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

    def clean_text(self):
        data = self.cleaned_data['text']
        if len(data) == 0:
            raise forms.ValidationError('И это весь комментарий? Пиши ещё!')
        return data

yatube/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import get_page_obj


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_obj = get_page_obj(post_list, request.GET.get('page'))

    context = {
        'page_obj': page_obj,
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = get_page_obj(post_list, request.GET.get('page'))

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = get_page_obj(post_list, request.GET.get('page'))
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author
        ).exists()
    context = {
        'posts_count': post_list.count(),
        'author': author,
        'page_obj': page_obj,
        'user': request.user,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    author = post.author
    context = {
        'author': author,
        'posts_count': author.posts.count(),
        'post': post,
        'form': form,
        'user': request.user,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        username = request.user.username

        return redirect('posts:profile', username=username)

    template = 'posts/create_post.html'
    context = {
        'groups': Group.objects.all(),
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        post.save()
        return redirect('posts:post_detail', post_id=post_id)

    template = 'posts/create_post.html'
    context = {
        'is_edit': True,
        'post_id': post_id,
        'post': post,
        'username': request.user,
        'form': form,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    current_user = request.user
    following_set = Follow.objects.filter(user=current_user)
    following_list = [follow.author for follow in following_set]
    post_list = Post.objects.filter(author__in=following_list)
    page_obj = get_page_obj(post_list, request.GET.get('page'))
    template = 'posts/follow.html'
    context = {
        'following_list': following_list,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    current_user = request.user
    author = get_object_or_404(User, username=username)
    is_already_follow = Follow.objects.filter(
        user=current_user,
        author=author
    ).exists()
    if not (current_user == author or is_already_follow):
        follow = Follow.objects.create(
            user=current_user,
            author=author
        )
        follow.save()
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    current_user = request.user
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        user=current_user,
        author=author
    )
    follow.delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
    {% if is_edit %}
        Редактирование поста
    {% else %}
        Новый пост
    {% endif %}
{% endblock %}
{% block content %}
                    <div class="row justify-content-center">
                        <div class="col-md-8 p-5">
                            <div class="card">
                                <div class="card-header">
                                    {% if is_edit %}
                                        Редактировать запись
                                    {% else %}
                                        Добавить запись
                                    {% endif %}
                                </div>
                                <div class="card-body">
                                    <form method="post"
                                          action={% if is_edit %}
                                              "{% url 'posts:post_edit' post_id%}"
                                          {% else %}
                                              "{% url 'posts:post_create' %}"
                                          {% endif %}
                                    enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% for field in form %}
                                        <div class="form-group row my-3 p-3">
                                            <label for="{{ field.id_for_label }}">
                                                {{ field.label }}
                                                {% if field.field.required %}
                                                    <span class="required text-danger">*</span>
                                                {% endif %}
                                            </label>
                                            {{ field|addclass:'form-control' }}
                                            {% if field.help_text %}
                                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                                    {{ field.help_text|safe }}
                                                </small>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                    <div class="d-flex justify-content-end">
                                        <button type="submit" class="btn btn-primary">
                                            {% if is_edit %}
                                                Сохранить
                                            {% else %}
                                                Добавить
                                            {% endif %}
                                        </button>
                                    </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}Избранное{% endblock %}
{% block content %}
                    {% include 'posts/includes/switcher.html' with follow=True %}
                    <div class="mb-5">
                        <ul>
                            {% for author in following_list %}
                                <li>
                                    <p>{{ author.get_user_name }}</p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% for post in page_obj %}
                        {% include 'posts/includes/post_list.html' %}
                        {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                        {% endif %}
                        {% if not forloop.last %}<hr>{% endif %}
                    {% endfor %}
                    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Записи сообщества {{ group.description }}{% endblock %}
{% block content %}
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_user_name }}
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "480x360" padding=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:index' %}">Вернуться на главную</a>
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' with index=True %}
                    {% for post in page_obj %}
                        {% include 'posts/includes/post_list.html' %}
                        <p>Комментариев: {{ post.comments.count }}</p>
                        {% if post.group %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                        {% endif %}
                        {% if not forloop.last %}
                        <hr>
                        {% endif %}
                    {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load user_filters %}

{% block title %}Пост {{ post.text|slice:':30' }}{% endblock %}
{% block content %}
                    <div class="row">
                        <aside class="col-12 col-md-3">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                                </li>
                                {% if post.group.id != None %}
                                    <li class="list-group-item">
                                        Группа: {{ post.group.title }}
                                        <a href="{% url 'posts:group_list' post.group.slug %}">
                                            все записи группы
                                        </a>
                                    </li>
                                {% endif %}
                                <li class="list-group-item">
                                    Автор: {{ author.get_user_name }}
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Всего постов автора:  <span >{{ posts_count }}</span>
                                </li>
                                <li class="list-group-item">
                                    <a href="{% url 'posts:profile' author.username %}">
                                        все посты пользователя
                                    </a>
                                </li>
                            </ul>
                        </aside>
                        <article class="col-12 col-md-9">

                            {% thumbnail post.image "480x360" padding=True as im %}
                                <img class="card-img my-2" src="{{ im.url }}">
                            {% endthumbnail %}

                            <p>
                                {{ post.text }}
                            </p>

                            {% if user == post.author %}
                                <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                                    Редактировать запись
                                </a>
                            {% endif %}

                            {% if user.is_authenticated %}
                                <div class="card my-4">
                                    <h5 class="card-header">Добавить комментарий:</h5>
                                    <div class="card-body">
                                        <form method="post" action="{% url 'posts:add_comment' post.id %}">
                                            {% csrf_token %}
                                            <div class="form-group mb-2">
                                                {{ form.text|addclass:"form-control" }}
                                            </div>
                                            <button type="submit" class="btn btn-primary">Отправить</button>
                                        </form>
                                    </div>
                                </div>
                            {% endif %}

                            {% for comment in comments %}
                                <div class="media mb-4">
                                    <div class="media-body">
                                        <h5 class="mt-0">
                                            <a href="{% url 'posts:profile' comment.author.username %}">
                                                {{ comment.author.username }}
                                            </a>
                                        </h5>
                                        <p>
                                            {{ comment.text }}
                                        </p>
                                    </div>
                                </div>
                            {% endfor %}
                        </article>
                    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ author.get_user_name }}{% endblock %}
{% block content %}
                    <div class="container py-5">
                        <h1>Все посты пользователя {{ author.get_user_name }}</h1>
                        <h3>Всего постов: {{ posts_count }}</h3>
                        {% if following %}
                        <a class="btn btn-lg btn-light" href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
                        {% else %}
                        <a class="btn btn-lg btn-primary" href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
                        {% endif %}
                        {% for post in page_obj %}
                        <article>
                            <ul>
                                <li>
                                    Автор: {{ author.get_user_name }}
                                    <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
                                </li>
                                <li>
                                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                                </li>
                            </ul>
                            {% thumbnail post.image "480x360" padding=True as im %}
                                <img class="card-img my-2" src="{{ im.url }}">
                            {% endthumbnail %}
                            <p>
                                {{ post.text }}
                            </p>
                            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
                        </article>
                        {% if post.group.id != None %}
                        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
                        {% endif %}
                        {% if not forloop.last %}<hr>{% endif %}
                        {% endfor %}
                        {% include 'posts/includes/paginator.html' %}
                    </div>
{% endblock %}